#!/usr/bin/env python3
"""Build the indexed Alien Syndrome bezel backdrop for the RTG presenter.

Preference order:
  1. assets/aliensyn_bezelproject.png  (Bezel Project artwork, if the user drops one in)
  2. a procedural generic bezel        (guaranteed -- the build can never fail here)

Output is identical in shape to the Shinobi tool it was adapted from:
  - build/bezel/shinobi_bezel_864x486.bin  (864x486 RGB332 indexed, pen 0 = hole)
  - source/hal/shinobi_rtg_bezel.h         (SHINOBI_RTG_* / SHINOBI_GAME_* macros)
so shinobi_rtg_bezeldata.s and shinobi_rtg_main.c need no changes.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SRC = ROOT / "assets" / "aliensyn_bezelproject.png"
OUT_DIR = ROOT / "source" / "build" / "bezel"
OUT_BIN = OUT_DIR / "shinobi_bezel_864x486.bin"
OUT_H = ROOT / "source" / "hal" / "shinobi_rtg_bezel.h"

RTG_W, RTG_H = 864, 486
ALPHA_HOLE = 16

# Centred play window for the procedural bezel (matches the proven Shinobi geometry).
HOLE_X, HOLE_Y, HOLE_W, HOLE_H = 116, 8, 632, 470


def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)


def write_header(minx, miny, maxx, maxy):
    OUT_H.write_text(
        "/* AUTO-GENERATED by make_aliensyn_rtg_bezel.py -- do not edit. */\n"
        "#ifndef SHINOBI_RTG_BEZEL_H\n"
        "#define SHINOBI_RTG_BEZEL_H\n"
        f"#define SHINOBI_RTG_W  {RTG_W}\n"
        f"#define SHINOBI_RTG_H  {RTG_H}\n"
        f"#define SHINOBI_GAME_X {minx}\n"
        f"#define SHINOBI_GAME_Y {miny}\n"
        f"#define SHINOBI_GAME_W {maxx - minx + 1}\n"
        f"#define SHINOBI_GAME_H {maxy - miny + 1}\n"
        "#endif\n"
    )


def from_png():
    from PIL import Image
    im = Image.open(SRC).convert("RGBA").resize((RTG_W, RTG_H), Image.Resampling.LANCZOS)
    px = im.load()

    minx, miny, maxx, maxy = RTG_W, RTG_H, -1, -1
    for y in range(RTG_H):
        for x in range(RTG_W):
            if px[x, y][3] < ALPHA_HOLE:
                minx = min(minx, x); miny = min(miny, y)
                maxx = max(maxx, x); maxy = max(maxy, y)
    if maxx < 0:
        raise SystemExit("no transparent playfield hole found in aliensyn bezel PNG")

    rgb = Image.new("RGB", (RTG_W, RTG_H), (0, 0, 0))
    rgb.paste(im, (0, 0), im)
    rpx = rgb.load()

    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        base = y * RTG_W
        for x in range(RTG_W):
            out[base + x] = 0 if px[x, y][3] < ALPHA_HOLE else rgb332(*rpx[x, y])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)
    write_header(minx, miny, maxx, maxy)
    print(f"  bezel {SRC.name} -> {OUT_BIN.name} ({RTG_W * RTG_H} bytes RGB332)")
    print(f"  hole/game window: x={minx} y={miny} w={maxx - minx + 1} h={maxy - miny + 1}")


def procedural():
    """A simple, self-contained bezel: dark vertical gradient with a bevelled
    frame around a centred transparent play window. Needs no external assets."""
    hx0, hy0 = HOLE_X, HOLE_Y
    hx1, hy1 = HOLE_X + HOLE_W - 1, HOLE_Y + HOLE_H - 1
    FRAME = 4  # bright bevel thickness around the window

    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        # dark space-blue gradient, top brighter than bottom
        t = y / (RTG_H - 1)
        bg_r = int(18 * (1.0 - t))
        bg_g = int(20 * (1.0 - t))
        bg_b = int(48 * (1.0 - t) + 8)
        bg = rgb332(bg_r, bg_g, bg_b)
        base = y * RTG_W
        in_y_hole = hy0 <= y <= hy1
        in_y_frame = (hy0 - FRAME) <= y <= (hy1 + FRAME)
        for x in range(RTG_W):
            if in_y_hole and hx0 <= x <= hx1:
                out[base + x] = 0  # transparent playfield hole
            elif in_y_frame and (hx0 - FRAME) <= x <= (hx1 + FRAME):
                out[base + x] = rgb332(196, 200, 224)  # bright bevel frame
            else:
                out[base + x] = bg

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)
    write_header(hx0, hy0, hx1, hy1)
    print(f"  bezel (procedural generic) -> {OUT_BIN.name} ({RTG_W * RTG_H} bytes RGB332)")
    print(f"  hole/game window: x={hx0} y={hy0} w={HOLE_W} h={HOLE_H}")


def main():
    if SRC.exists():
        try:
            from_png()
            return
        except Exception as e:  # noqa: BLE001 -- fall back rather than fail the build
            print(f"  aliensyn bezel PNG present but unusable ({e}); using procedural bezel")
    procedural()


if __name__ == "__main__":
    main()
