/* AUTO-GENERATED by make_aliensyn_rtg_bezel.py -- do not edit. */
#ifndef SHINOBI_RTG_BEZEL_H
#define SHINOBI_RTG_BEZEL_H
#define SHINOBI_RTG_W  864
#define SHINOBI_RTG_H  486
#define SHINOBI_GAME_X 116
#define SHINOBI_GAME_Y 8
#define SHINOBI_GAME_W 632
#define SHINOBI_GAME_H 470
#endif
