#!/usr/bin/env python3
"""Build the indexed Shadow Dancer Bezel Project backdrop for the RTG presenter.

Prefers a Shadow Dancer-specific bezel PNG if present, then falls back to any
available Sega-cabinet bezel art, and finally synthesises a solid black bezel
with a centred 4:3 playfield hole so the build never fails on a missing PNG.
"""
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
ASSETS = ROOT / "assets"
# First existing candidate wins; None (no PNG) => synthesise a solid bezel.
SRC_CANDIDATES = [
    "shadowdancer_bezelproject.png",
    "shdancer_bezelproject.png",
    "goldenaxe_bezelproject.png",
    "shinobi_bezelproject.png",
]
OUT_DIR = ROOT / "source" / "build" / "bezel"
OUT_BIN = OUT_DIR / "shinobi_bezel_864x486.bin"
OUT_H = ROOT / "source" / "hal" / "shinobi_rtg_bezel.h"

RTG_W, RTG_H = 864, 486
ALPHA_HOLE = 16


def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)


def pick_source():
    for name in SRC_CANDIDATES:
        p = ASSETS / name
        if p.is_file():
            return p
    return None


def synth_solid():
    """Solid black bezel, centred 4:3 hole (pen 0 = transparent playfield)."""
    hole_w = int(RTG_H * 4 / 3)
    if hole_w > RTG_W:
        hole_w = RTG_W
    hole_h = RTG_H
    minx = (RTG_W - hole_w) // 2
    miny = (RTG_H - hole_h) // 2
    maxx = minx + hole_w - 1
    maxy = miny + hole_h - 1
    out = bytearray(RTG_W * RTG_H)  # all zero = black + hole; renderer keys off pen 0
    return out, minx, miny, maxx, maxy


def main():
    SRC = pick_source()
    if SRC is None:
        print("  no bezel PNG found -- synthesising solid black bezel")
        out, minx, miny, maxx, maxy = synth_solid()
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        OUT_BIN.write_bytes(out)
        write_header(minx, miny, maxx, maxy)
        print(f"  hole/game window: x={minx} y={miny} w={maxx - minx + 1} h={maxy - miny + 1}")
        return

    im = Image.open(SRC).convert("RGBA").resize((RTG_W, RTG_H), Image.Resampling.LANCZOS)
    px = im.load()

    minx, miny, maxx, maxy = RTG_W, RTG_H, -1, -1
    for y in range(RTG_H):
        for x in range(RTG_W):
            if px[x, y][3] < ALPHA_HOLE:
                minx = min(minx, x)
                miny = min(miny, y)
                maxx = max(maxx, x)
                maxy = max(maxy, y)

    if maxx < 0:
        # No transparent playfield hole in the art -- fall back to a solid bezel.
        print(f"  {SRC.name} has no transparent hole -- synthesising solid bezel")
        out, minx, miny, maxx, maxy = synth_solid()
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        OUT_BIN.write_bytes(out)
        write_header(minx, miny, maxx, maxy)
        print(f"  hole/game window: x={minx} y={miny} w={maxx - minx + 1} h={maxy - miny + 1}")
        return

    rgb = Image.new("RGB", (RTG_W, RTG_H), (0, 0, 0))
    rgb.paste(im, (0, 0), im)
    rpx = rgb.load()

    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        base = y * RTG_W
        for x in range(RTG_W):
            out[base + x] = 0 if px[x, y][3] < ALPHA_HOLE else rgb332(*rpx[x, y])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)
    write_header(minx, miny, maxx, maxy)
    print(f"  bezel {SRC.name} -> {OUT_BIN.name} ({RTG_W * RTG_H} bytes RGB332)")
    print(f"  hole/game window: x={minx} y={miny} w={maxx - minx + 1} h={maxy - miny + 1}")


def write_header(minx, miny, maxx, maxy):
    OUT_H.write_text(
        "/* AUTO-GENERATED by make_shinobi_rtg_bezel.py -- do not edit. */\n"
        "#ifndef SHINOBI_RTG_BEZEL_H\n"
        "#define SHINOBI_RTG_BEZEL_H\n"
        f"#define SHINOBI_RTG_W  {RTG_W}\n"
        f"#define SHINOBI_RTG_H  {RTG_H}\n"
        f"#define SHINOBI_GAME_X {minx}\n"
        f"#define SHINOBI_GAME_Y {miny}\n"
        f"#define SHINOBI_GAME_W {maxx - minx + 1}\n"
        f"#define SHINOBI_GAME_H {maxy - miny + 1}\n"
        "#endif\n"
    )


if __name__ == "__main__":
    main()
