#!/usr/bin/env python3
"""Build the indexed Shinobi Bezel Project backdrop for the RTG presenter."""
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SRC = ROOT / "assets" / "shinobi_bezelproject.png"
OUT_DIR = ROOT / "source" / "build" / "bezel"
OUT_BIN = OUT_DIR / "shinobi_bezel_864x486.bin"
OUT_H = ROOT / "source" / "hal" / "shinobi_rtg_bezel.h"

RTG_W, RTG_H = 864, 486
ALPHA_HOLE = 16


def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)


def main():
    im = Image.open(SRC).convert("RGBA").resize((RTG_W, RTG_H), Image.Resampling.LANCZOS)
    px = im.load()

    minx, miny, maxx, maxy = RTG_W, RTG_H, -1, -1
    for y in range(RTG_H):
        for x in range(RTG_W):
            if px[x, y][3] < ALPHA_HOLE:
                minx = min(minx, x)
                miny = min(miny, y)
                maxx = max(maxx, x)
                maxy = max(maxy, y)

    if maxx < 0:
        raise SystemExit("no transparent playfield hole found in Shinobi bezel PNG")

    rgb = Image.new("RGB", (RTG_W, RTG_H), (0, 0, 0))
    rgb.paste(im, (0, 0), im)
    rpx = rgb.load()

    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        base = y * RTG_W
        for x in range(RTG_W):
            out[base + x] = 0 if px[x, y][3] < ALPHA_HOLE else rgb332(*rpx[x, y])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)
    OUT_H.write_text(
        "/* AUTO-GENERATED by make_shinobi_rtg_bezel.py -- do not edit. */\n"
        "#ifndef SHINOBI_RTG_BEZEL_H\n"
        "#define SHINOBI_RTG_BEZEL_H\n"
        f"#define SHINOBI_RTG_W  {RTG_W}\n"
        f"#define SHINOBI_RTG_H  {RTG_H}\n"
        f"#define SHINOBI_GAME_X {minx}\n"
        f"#define SHINOBI_GAME_Y {miny}\n"
        f"#define SHINOBI_GAME_W {maxx - minx + 1}\n"
        f"#define SHINOBI_GAME_H {maxy - miny + 1}\n"
        "#endif\n"
    )
    print(f"  bezel {SRC.name} -> {OUT_BIN.name} ({RTG_W * RTG_H} bytes RGB332)")
    print(f"  hole/game window: x={minx} y={miny} w={maxx - minx + 1} h={maxy - miny + 1}")


if __name__ == "__main__":
    main()
